-keep class !com.playgamesinteractive.lushlicense.** { *; }
-keep class com.playgamesinteractive.lushlicense.internal.LicenseStateMachine { *; }
-keepattributes *Annotation*
-dontwarn **
-dontnote **
